// mutation global
export const SET_TOAST = 'SET_TOAST'
export const SET_LOADING = 'SET_LOADING'
export const SET_API_LOADING = 'SET_API_LOADING'
export const SET_POPUP = 'SET_POPUP'
export const SET_NAV = 'SET_NAV'
export const SET_BUCKET = 'SET_BUCKET'

// mutation
export const SET_MAP = 'SET_MAP'
export const SET_MAP_SELECTED_MARKER = 'SET_MAP_SELECTED_MARKER'
export const SET_MAP_FILTERS_FORM = 'SET_MAP_FILTERS_FORM'

// action global
export const OPEN_TOAST = 'tOPEN_TOAST'
export const OPEN_LOADING = 'OPEN_LOADING'
export const CLOSE_LOADING = 'CLOSE_LOADING'
export const OPEN_API_LOADING = 'OPEN_API_LOADING'
export const CLOSE_API_LOADING = 'CLOSE_API_LOADING'
export const CHANGE_NAV = 'CHANGE_NAV'
export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'
export const FILL_BUCKET = 'FILL_BUCKET'
export const FALL_BUCKET = 'FALL_BUCKET'

// action
export const UPDATE_MAP_MARKERS = 'UPDATE_MAP_MARKERS'
export const UPDATE_MAP_SEARCH = 'UPDATE_MAP_SEARCH'

// api
export const FETCH_CODE_GET = 'FETCH_CODE_GET'
export const FETCH_USERS_GET = 'FETCH_CODE_GET'
export const FETCH_USERS_UPDATE = 'FETCH_USERS_UPDATE'
export const FETCH_USERS_OAUTH = 'FETCH_USERS_OAUTH'
export const FETCH_USERS_COLLECTS_GET = 'FETCH_USERS_COLLECTS_GET'
export const FETCH_USERS_COLLECTS_POST = 'FETCH_USERS_COLLECTS_POST'
export const FETCH_USERS_COLLECTS_DEL = 'FETCH_USERS_COLLECTS_DEL'
export const FETCH_MAP_SEARCH = 'FETCH_MAP_SEARCH'
export const FETCH_DETAIL = 'FETCH_DETAIL'

// http code
export const UNKOWN_HTTP_ERROR = 'UNKOWN_HTTP_ERROR'

// route type
export const ROUTE_TYPE_REPLACE = 'ROUTE_TYPE_REPLACE'
